# Generated by Django 3.2.19 on 2026-06-26 06:28

from django.db import migrations, models
import movies.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[movies.validators.validate_youtube_url]),
        ),
    ]
