# Generated by Django 3.2.19 on 2026-07-11 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0006_auto_20260709_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_token', models.UUIDField(db_index=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.booking')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.paymenttransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='bookingemailnotification',
            index=models.Index(fields=['status', 'next_retry_at'], name='email_status_retry_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingemailnotification',
            index=models.Index(fields=['created_at'], name='email_created_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingemailnotification',
            index=models.Index(fields=['sent_at'], name='email_sent_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingemailnotification',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_transaction__isnull', False)), fields=('payment_transaction',), name='unique_email_per_payment'),
        ),
    ]
